[package]

name = "openssl2-sys"
version = "1.0.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
links = "openssl"
build = "src/build.rs"

[features]
tlsv1_2 = []
tlsv1_1 = []
sslv2 = []
aes_xts = []

[build-dependencies.pkg-config]
version = "*"
